name: Scan Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag local/scanimage:latest
    - uses: anchore/scan-action@main
      id: scan
      with:
        image: "local/scanimage:latest"
        # fail-build: true
        acs-report-enable: true
    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}

    # - name: anchore inline scan JSON results
    #   run: for j in `ls ./anchore-reports/*.json`; do echo "---- ${j} ----"; cat ${j}; echo; done
    #
    - uses: azure/container-scan@v0
      with:
        image-name: local/scanimage:latest
# Add Serif report once Code Scanner is out of beta stage
